### ISSUE TITLE
Spreading the nodes wtr to each others ?

### ISSUE THREAD

**Issue by aymeric75** [Oneiroe/PySimpleAutomata#10]
Hi,

I could eventually generate a DFA for Hanoi-4-4 (there should be 256 nodes and 1452 transitions) but the graph I obtain is very messy:

![DFA-Hanoi_4_4 dot](https://github.com/Oneiroe/PySimpleAutomata/assets/12927600/ae564b74-782d-431c-ad0a-c47267027e79)

Is there a way to spread the different nodes wtr to each others ?

Thanks

**Comment by Oneiroe** [comment]
Please for Graphviz support refer to the Graphviz community. They can provide a more in-depth solution to your doubts and point you toward the best usage of the tool.
