### ISSUE TITLE
Feature request: Ability to convert NFA (NDFA) to DFA

### ISSUE THREAD

**Issue by flysand7** [Oneiroe/PySimpleAutomata#3]
It is a commonly known fact that the class of non-deterministic finite automation is equivalent to the class deterministic finite automation, i.e. every non-deterministic finite automation can be converted to deterministic finite automation. There exist an algorithm that performs the given task, in particular a [Subset Construction Method](https://en.wikipedia.org/wiki/Powerset_construction)

I was expecting this package to provide such functionality but turned out that it didn't have such.

**Comment by Oneiroe** [comment]
As written in the documentation, the determinization of NFAs is already provided by this package through the function [nfa_determinization() ](https://pysimpleautomata.readthedocs.io/en/latest/NFA.html#PySimpleAutomata.NFA.nfa_determinization).
